version: '3'
services: #containers
  web: #putting up inital container
    build: 
      #this context option is essentially specifying where we want all the files and folders for this image to be pulled from.
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
     - /usr/app/node_modules
     - .:/usr/ap  
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /usr/app/node_modules
      - .:/usr/app
    command: ["npm", "run", "test"]